from feedgen.feed import FeedGenerator
fg = FeedGenerator()
fg.load_extension('podcast')
fg.podcast.itunes_category('Technology', 'Podcasting')
fg.title('Some Testfeed')
fg.link( href='http://example.com', rel='alternate' )
fg.description('yeah yeah')
fg.language('en')
fe = fg.add_entry()
fe.id('http://lernfunk.de/media/654321/1/file.mp3')
fe.title('The First Episode')
fe.description('Enjoy our first episode.')
fe.enclosure('http://lernfunk.de/media/654321/1/file.mp3', 0, 'audio/mpeg')
fg.rss_str(pretty=True)
fg.rss_file('podcast.xml')
